/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


public class EditEmployeeJFrame extends javax.swing.JFrame {

    public MyHashTable theHT;
    
    public EditEmployeeJFrame() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable theHTrefval){
        theHT = theHTrefval;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        employeenumber_txt = new javax.swing.JFormattedTextField();
        edit_button = new javax.swing.JButton();
        firstname_txt = new javax.swing.JTextField();
        lastname_txt = new javax.swing.JTextField();
        deductrate_txt = new javax.swing.JTextField();
        PTE_radiobutton = new javax.swing.JRadioButton();
        FTE_radiobutton = new javax.swing.JRadioButton();
        PTEhourlywage_txt = new javax.swing.JTextField();
        PTEhoursperweek_txt = new javax.swing.JTextField();
        PTEweeksperyear_txt = new javax.swing.JTextField();
        FTEyearlysalary_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        worklocation_txt = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Title.setText("Edit Employee");

        employeenumber_txt.setText("Employee Number");

        edit_button.setText("Edit Employee");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        firstname_txt.setText("First Name");
        firstname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_txtActionPerformed(evt);
            }
        });

        lastname_txt.setText("Last Name");

        deductrate_txt.setText("Deduct Rate");

        PTE_radiobutton.setText("PTE");
        PTE_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTE_radiobuttonActionPerformed(evt);
            }
        });

        FTE_radiobutton.setText("FTE");
        FTE_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTE_radiobuttonActionPerformed(evt);
            }
        });

        PTEhourlywage_txt.setText("PTE hourly wage");

        PTEhoursperweek_txt.setText("PTE hours per week");

        PTEweeksperyear_txt.setText("PTE weeks per year");

        FTEyearlysalary_txt.setText("FTE yearly salary");

        gender_txt.setText("Gender");

        worklocation_txt.setText("Work Location");

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeenumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_button))
                    .addComponent(deductrate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FTEyearlysalary_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PTEhourlywage_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PTE_radiobutton)
                                .addGap(18, 18, 18)
                                .addComponent(FTE_radiobutton))
                            .addComponent(edit_button, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PTEhoursperweek_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PTEweeksperyear_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(worklocation_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeenumber_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(worklocation_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deductrate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTE_radiobutton)
                    .addComponent(FTE_radiobutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTEhourlywage_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTEhoursperweek_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PTEweeksperyear_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(FTEyearlysalary_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit_button)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        // edit button is pressed
        
        // Set variables
        int employeeNumber = Integer.parseInt(employeenumber_txt.getText()); // beware you can change emp number causing a new employee to be added instead
        String firstName = firstname_txt.getText();
        String lastName = lastname_txt.getText();
        String gender = gender_txt.getText();
        String workLocation = worklocation_txt.getText();
        double deductRate = Double.parseDouble(deductrate_txt.getText());
        
        //Remove employee first
        theHT.removeEmployee(employeeNumber);
        
        if (FTE_radiobutton.isSelected()) {
            System.out.println("Saving full time employee.");
            double yearlySalary = Double.parseDouble(FTEyearlysalary_txt.getText()); 
            FTE newFTE;
            newFTE = new FTE(employeeNumber, firstName, lastName, gender, workLocation, deductRate, yearlySalary);
            theHT.addEmployee(newFTE);
            System.out.println("Successfully edited " + newFTE.firstName);
        } else if (PTE_radiobutton.isSelected()) {
            System.out.println("Saving part time employee.");
            double hourlyWage = Double.parseDouble(PTEhourlywage_txt.getText());
            double hoursPerWeek = Double.parseDouble(PTEhoursperweek_txt.getText());
            double weeksPerYear = Double.parseDouble(PTEweeksperyear_txt.getText());
            PTE newPTE;
            newPTE = new PTE(employeeNumber, firstName, lastName, gender, workLocation, deductRate, hourlyWage, hoursPerWeek, weeksPerYear);
            theHT.addEmployee(newPTE);
            System.out.println("Successfully edited " + newPTE.firstName);
        }
        
        
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void firstname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname_txtActionPerformed

    private void PTE_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTE_radiobuttonActionPerformed
        // PTE
        FTE_radiobutton.setSelected(false);
        PTEhourlywage_txt.setVisible(true);
        PTEhoursperweek_txt.setVisible(true);
        PTEweeksperyear_txt.setVisible(true);
        FTEyearlysalary_txt.setVisible(false);
    }//GEN-LAST:event_PTE_radiobuttonActionPerformed

    private void FTE_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTE_radiobuttonActionPerformed
        // FTE
        PTE_radiobutton.setSelected(false);
        PTEhourlywage_txt.setVisible(false);
        PTEhoursperweek_txt.setVisible(false);
        PTEweeksperyear_txt.setVisible(false);
        FTEyearlysalary_txt.setVisible(true);
    }//GEN-LAST:event_FTE_radiobuttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // search button pressed -> load data
        int employeeNumber = Integer.parseInt(employeenumber_txt.getText());
        EmployeeInfo employee = theHT.searchByEmployeeNumber(employeeNumber);
        if (employee != null) {
            System.out.println("Employee Found");
            firstname_txt.setText(employee.getFirstName());
            lastname_txt.setText(employee.getLastName());
            gender_txt.setText(employee.getGender());
            worklocation_txt.setText(employee.getWorkLoc());
            deductrate_txt.setText(Double.toString(employee.getDeductRate()));
            if (employee instanceof PTE) {
                PTE PTEemployee = (PTE) employee; // cast into FTE
                
                PTEhourlywage_txt.setText(Double.toString(PTEemployee.getHourlyWage()));
                PTEhoursperweek_txt.setText(Double.toString(PTEemployee.getHoursPerWeek()));
                PTEweeksperyear_txt.setText(Double.toString(PTEemployee.getWeeksPerYear()));
                // hide FTE
                PTE_radiobutton.setSelected(true);
                FTE_radiobutton.setSelected(false);
                FTEyearlysalary_txt.setVisible(false);
                
            } else if (employee instanceof FTE) {
                FTE FTEemployee = (FTE) employee; // cast into FTE
                FTEyearlysalary_txt.setText(Double.toString(FTEemployee.getYearlySalary()));
                // hide PTE
                PTE_radiobutton.setSelected(false);
                FTE_radiobutton.setSelected(true);
                PTEhourlywage_txt.setVisible(false);
                PTEhoursperweek_txt.setVisible(false);
                PTEweeksperyear_txt.setVisible(false);
            }
        } else {
            System.out.println("Employee Not Found");
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FTE_radiobutton;
    private javax.swing.JTextField FTEyearlysalary_txt;
    private javax.swing.JRadioButton PTE_radiobutton;
    private javax.swing.JTextField PTEhourlywage_txt;
    private javax.swing.JTextField PTEhoursperweek_txt;
    private javax.swing.JTextField PTEweeksperyear_txt;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField deductrate_txt;
    private javax.swing.JButton edit_button;
    private javax.swing.JFormattedTextField employeenumber_txt;
    private javax.swing.JTextField firstname_txt;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JTextField lastname_txt;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField worklocation_txt;
    // End of variables declaration//GEN-END:variables
}
