/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ariel
 */
public class SearchEmployee extends javax.swing.JFrame {
    
    // Attributes
    public MyHashTable theHT;
    
    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
        
    }

    public void setMainHT(MyHashTable theHTrefval){
        theHT = theHTrefval;
        SetAllLabelsVisibility(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EmpNum_input = new javax.swing.JTextField();
        Search_button = new javax.swing.JButton();
        firstname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        deductrate = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        worklocation = new javax.swing.JLabel();
        PTEhourlywage = new javax.swing.JLabel();
        PTEhoursperweek = new javax.swing.JLabel();
        PTEweeksperyear = new javax.swing.JLabel();
        FTEyearlysalary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel1.setText("Search for an employee's information");

        EmpNum_input.setText("Employee Number");
        EmpNum_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNum_inputActionPerformed(evt);
            }
        });

        Search_button.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        Search_button.setText("Search Employees");
        Search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_buttonActionPerformed(evt);
            }
        });

        firstname.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        firstname.setText("jLabel2");

        lastname.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lastname.setText("jLabel2");

        deductrate.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        deductrate.setText("jLabel2");

        gender.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        gender.setText("jLabel2");

        worklocation.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        worklocation.setText("jLabel2");

        PTEhourlywage.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        PTEhourlywage.setText("jLabel2");

        PTEhoursperweek.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        PTEhoursperweek.setText("jLabel2");

        PTEweeksperyear.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        PTEweeksperyear.setText("jLabel2");

        FTEyearlysalary.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        FTEyearlysalary.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(worklocation)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpNum_input, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender)
                            .addComponent(deductrate)
                            .addComponent(lastname)
                            .addComponent(firstname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FTEyearlysalary)
                            .addComponent(PTEweeksperyear)
                            .addComponent(PTEhoursperweek)
                            .addComponent(PTEhourlywage)
                            .addComponent(Search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpNum_input, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deductrate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PTEhourlywage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PTEhoursperweek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PTEweeksperyear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FTEyearlysalary)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(worklocation)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SetAllLabelsVisibility(boolean visibility){
        deductrate.setVisible(visibility);
        firstname.setVisible(visibility);
        lastname.setVisible(visibility);
        gender.setVisible(visibility);
        worklocation.setVisible(visibility);
        FTEyearlysalary.setVisible(visibility);
        PTEhourlywage.setVisible(visibility);
        PTEhoursperweek.setVisible(visibility);
        PTEweeksperyear.setVisible(visibility);
    }
    
    private void SearchForEmployee(){
        try { // try to read the integer the user inputed
            int NumEmployees = Integer.parseInt(EmpNum_input.getText());
        } catch (Exception e) {
            System.out.println("You must enter an integer.");
            Error("You must enter an integer.");
            return;
        }
        int NumEmployees = Integer.parseInt(EmpNum_input.getText()); // employee number from input
        
        EmployeeInfo employeeToSearch = theHT.searchByEmployeeNumber(NumEmployees); // find employee
        if (employeeToSearch == null) {
            System.out.println("Employee not found.");
            Error("Employee not found.");
            return;
        }        
        deductrate.setText("Deduct rate: " + Double.toString(employeeToSearch.getDeductRate()));
        firstname.setText("First name: " + employeeToSearch.getFirstName());
        lastname.setText("Last name: " + employeeToSearch.getLastName());
        gender.setText("Gender: " + employeeToSearch.getGender());
        worklocation.setText("Work location: " + employeeToSearch.getWorkLoc());
        
        SetAllLabelsVisibility(true); // Set all labels to visible
        
        // Determine if PTE or FTE to display PTE or FTE properties
        String PTEorFTE = employeeToSearch.PTEorFTE(employeeToSearch);
        if (PTEorFTE.equals("PTE")) { // Set labels for PTE attributes if PTE
            PTE PTEemployee = (PTE) employeeToSearch;
            PTEhourlywage.setText("Hourly wage: " + Double.toString(PTEemployee.hourlyWage));
            PTEhoursperweek.setText("Hours per week: " + Double.toString(PTEemployee.hoursPerWeek));
            PTEweeksperyear.setText("Weeks per year: " + Double.toString(PTEemployee.weeksPerYear));
            
            // Set FTE labels to false
            FTEyearlysalary.setVisible(false);
            
        } else if (PTEorFTE.equals("FTE")) { // set labels for FTE attributes if FTE
            FTE FTEemployee = (FTE) employeeToSearch;
            FTEyearlysalary.setText("Yearly salary: " + Double.toString(FTEemployee.yearlySalary));
            
            // Set PTE labels to false
            PTEhourlywage.setVisible(false);
            PTEhoursperweek.setVisible(false);
            PTEweeksperyear.setVisible(false);
            
        } else {
            System.out.println("Employee is neither PTE or FTE? Something has gone wrong");
        }
        
    }
    
    public void Error(String errormsg){
        ErrorPopup errorWindow = new ErrorPopup();
        errorWindow.setVisible(true);
        errorWindow.setErrorLabel(errormsg);
    }
    
    private void EmpNum_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNum_inputActionPerformed
        // Run function to search
        SearchForEmployee();
    }//GEN-LAST:event_EmpNum_inputActionPerformed

    private void Search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_buttonActionPerformed
        // Run function to search
        SearchForEmployee();
    }//GEN-LAST:event_Search_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpNum_input;
    private javax.swing.JLabel FTEyearlysalary;
    private javax.swing.JLabel PTEhourlywage;
    private javax.swing.JLabel PTEhoursperweek;
    private javax.swing.JLabel PTEweeksperyear;
    private javax.swing.JButton Search_button;
    private javax.swing.JLabel deductrate;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel worklocation;
    // End of variables declaration//GEN-END:variables
}
